name: C Build, Test, and Release Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the project
      run: |
        make
        if [ ! -f ./example ]; then
          echo "Error: './example' binary not found after build!" >&2
          exit 1
        fi
 
