name: C Build, Test, and Release Example

permissions:
  contents: write
  issues: write
  pull-requests: write
  deployments: write
  actions: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the project
      run: |
        make
        if [ ! -f ./example ]; then
          echo "Error: './example' binary not found after build!" >&2
          exit 1
        fi
          
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@release-1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './example'
