name: C Build, Test, and Release Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  release:
    types: [ "published" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build the project
      run: |
        make
        if [ ! -f ./example ]; then
          echo "Error: './example' binary not found after build!" >&2
          exit 1
        fi

    - name: Upload Release Asset
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./example
        asset_name: example
        asset_content_type: application/octet-stream
